//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/ArrayUtils.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _KTUtilArrayUtils_H_
#define _KTUtilArrayUtils_H_

@class IOSBooleanArray;
@class IOSByteArray;
@class IOSCharArray;
@class IOSDoubleArray;
@class IOSFloatArray;
@class IOSIntArray;
@class IOSLongArray;
@class IOSObjectArray;
@class IOSShortArray;

#import "JreEmulation.h"

@interface KTUtilArrayUtils : NSObject {
}

+ (IOSObjectArray *)concatWithNSObjectArray:(IOSObjectArray *)array1
                          withNSObjectArray:(IOSObjectArray *)array2;

+ (IOSBooleanArray *)concatWithBooleanArray:(IOSBooleanArray *)array1
                           withBooleanArray:(IOSBooleanArray *)array2;

+ (IOSByteArray *)concatWithByteArray:(IOSByteArray *)array1
                        withByteArray:(IOSByteArray *)array2;

+ (IOSShortArray *)concatWithShortArray:(IOSShortArray *)array1
                         withShortArray:(IOSShortArray *)array2;

+ (IOSIntArray *)concatWithIntArray:(IOSIntArray *)array1
                       withIntArray:(IOSIntArray *)array2;

+ (IOSLongArray *)concatWithLongArray:(IOSLongArray *)array1
                        withLongArray:(IOSLongArray *)array2;

+ (IOSFloatArray *)concatWithFloatArray:(IOSFloatArray *)array1
                         withFloatArray:(IOSFloatArray *)array2;

+ (IOSDoubleArray *)concatWithDoubleArray:(IOSDoubleArray *)array1
                          withDoubleArray:(IOSDoubleArray *)array2;

+ (IOSCharArray *)concatWithCharArray:(IOSCharArray *)array1
                        withCharArray:(IOSCharArray *)array2;

+ (IOSCharArray *)concatWithCharArray2:(IOSObjectArray *)arrays;

+ (IOSByteArray *)toBytesWithCharArray:(IOSCharArray *)chars;

+ (IOSCharArray *)toCharsWithByteArray:(IOSByteArray *)data;

+ (IOSByteArray *)xor__WithByteArray:(IOSByteArray *)b1
                       withByteArray:(IOSByteArray *)b2;

- (id)init;

@end

__attribute__((always_inline)) inline void KTUtilArrayUtils_init() {}

typedef KTUtilArrayUtils ComKloudtekUtilArrayUtils;

#endif // _KTUtilArrayUtils_H_
