//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/crypto/AsymmetricAlgorithm.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _ComKloudtekUtilCryptoAsymmetricAlgorithm_H_
#define _ComKloudtekUtilCryptoAsymmetricAlgorithm_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef enum {
  ComKloudtekUtilCryptoAsymmetricAlgorithm_RSA = 0,
} ComKloudtekUtilCryptoAsymmetricAlgorithm;

@interface ComKloudtekUtilCryptoAsymmetricAlgorithmEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *jceId_;
  NSString *cryptAlg_;
}
+ (IOSObjectArray *)values;
+ (ComKloudtekUtilCryptoAsymmetricAlgorithmEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;

- (id)initWithNSString:(NSString *)jceId
          withNSString:(NSString *)cryptAlg
          withNSString:(NSString *)__name
               withInt:(int)__ordinal;

- (id)initWithNSString:(NSString *)jceId
          withNSString:(NSString *)__name
               withInt:(int)__ordinal;

- (NSString *)getJceId;

- (NSString *)getCryptAlg;
@end

FOUNDATION_EXPORT BOOL ComKloudtekUtilCryptoAsymmetricAlgorithmEnum_initialized;
J2OBJC_STATIC_INIT(ComKloudtekUtilCryptoAsymmetricAlgorithmEnum)

FOUNDATION_EXPORT ComKloudtekUtilCryptoAsymmetricAlgorithmEnum *ComKloudtekUtilCryptoAsymmetricAlgorithmEnum_values[];

#define ComKloudtekUtilCryptoAsymmetricAlgorithmEnum_RSA ComKloudtekUtilCryptoAsymmetricAlgorithmEnum_values[ComKloudtekUtilCryptoAsymmetricAlgorithm_RSA]
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoAsymmetricAlgorithmEnum, RSA, ComKloudtekUtilCryptoAsymmetricAlgorithmEnum *)

J2OBJC_FIELD_SETTER(ComKloudtekUtilCryptoAsymmetricAlgorithmEnum, jceId_, NSString *)
J2OBJC_FIELD_SETTER(ComKloudtekUtilCryptoAsymmetricAlgorithmEnum, cryptAlg_, NSString *)

#endif // _ComKloudtekUtilCryptoAsymmetricAlgorithm_H_
