//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/BaseNCodec.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _KTUtilsBaseNCodec_H_
#define _KTUtilsBaseNCodec_H_

@class IOSByteArray;
@class KTUtilsBaseNCodec_Context;

#import "JreEmulation.h"

#define KTUtilsBaseNCodec_DEFAULT_BUFFER_RESIZE_FACTOR 2
#define KTUtilsBaseNCodec_DEFAULT_BUFFER_SIZE 8192
#define KTUtilsBaseNCodec_EOF -1
#define KTUtilsBaseNCodec_MASK_8BITS 255
#define KTUtilsBaseNCodec_MIME_CHUNK_SIZE 76
#define KTUtilsBaseNCodec_PAD_DEFAULT 61
#define KTUtilsBaseNCodec_PEM_CHUNK_SIZE 64

@interface KTUtilsBaseNCodec : NSObject {
 @public
  char PAD_;
  int unencodedBlockSize_;
  int encodedBlockSize_;
  int lineLength_;
  int chunkSeparatorLength_;
}

+ (int)getEOF;
+ (int)MIME_CHUNK_SIZE;
+ (int)PEM_CHUNK_SIZE;
+ (int)MASK_8BITS;
+ (char)PAD_DEFAULT;
- (id)initWithInt:(int)unencodedBlockSize
          withInt:(int)encodedBlockSize
          withInt:(int)lineLength
          withInt:(int)chunkSeparatorLength;
- (BOOL)hasDataWithKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (int)availableWithKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (int)getDefaultBufferSize;
- (IOSByteArray *)resizeBufferWithKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (IOSByteArray *)ensureBufferSizeWithInt:(int)size
            withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (int)readResultsWithByteArray:(IOSByteArray *)b
                        withInt:(int)bPos
                        withInt:(int)bAvail
  withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
+ (BOOL)isWhiteSpaceWithByte:(char)byteToCheck;
- (id)encodeWithId:(id)obj;
- (NSString *)encodeToStringWithByteArray:(IOSByteArray *)pArray;
- (NSString *)encodeAsStringWithByteArray:(IOSByteArray *)pArray;
- (id)decodeWithId:(id)obj;
- (IOSByteArray *)decodeWithNSString:(NSString *)pArray;
- (IOSByteArray *)decodeWithByteArray:(IOSByteArray *)pArray;
- (IOSByteArray *)encodeWithByteArray:(IOSByteArray *)pArray;
- (void)encodeWithByteArray:(IOSByteArray *)pArray
                    withInt:(int)i
                    withInt:(int)length
withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (void)decodeWithByteArray:(IOSByteArray *)pArray
                    withInt:(int)i
                    withInt:(int)length
withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (BOOL)isInAlphabetWithByte:(char)value;
- (BOOL)isInAlphabetWithByteArray:(IOSByteArray *)arrayOctet
                      withBoolean:(BOOL)allowWSPad;
- (BOOL)isInAlphabetWithNSString:(NSString *)basen;
- (BOOL)containsAlphabetOrPadWithByteArray:(IOSByteArray *)arrayOctet;
- (long long int)getEncodedLengthWithByteArray:(IOSByteArray *)pArray;
- (void)copyAllFieldsTo:(KTUtilsBaseNCodec *)other;
@end

typedef KTUtilsBaseNCodec ComKloudtekUtilBaseNCodec;

@interface KTUtilsBaseNCodec_Context : NSObject {
 @public
  int ibitWorkArea_;
  long long int lbitWorkArea_;
  IOSByteArray *buffer_;
  int pos_;
  int readPos_;
  BOOL eof_;
  int currentLinePos_;
  int modulus_;
}

- (id)init;
- (NSString *)description;
- (void)copyAllFieldsTo:(KTUtilsBaseNCodec_Context *)other;
@end

J2OBJC_FIELD_SETTER(KTUtilsBaseNCodec_Context, buffer_, IOSByteArray *)

#endif // _KTUtilsBaseNCodec_H_
