//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/Base64.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _KTUtilBase64_H_
#define _KTUtilBase64_H_

@class IOSByteArray;
@class JavaMathBigInteger;
@class KTUtilBaseNCodec_Context;

#import "JreEmulation.h"
#include "BaseNCodec.h"

#define KTUtilBase64_BITS_PER_ENCODED_BYTE 6
#define KTUtilBase64_BYTES_PER_ENCODED_BLOCK 4
#define KTUtilBase64_BYTES_PER_UNENCODED_BLOCK 3
#define KTUtilBase64_MASK_6BITS 63

@interface KTUtilBase64 : KTUtilBaseNCodec {
 @public
  IOSByteArray *encodeTable_;
  IOSByteArray *decodeTable_;
  IOSByteArray *lineSeparator_;
  int decodeSize_;
  int encodeSize_;
}

- (id)init;

- (id)initWithBoolean:(BOOL)urlSafe;

- (id)initWithInt:(int)lineLength;

- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator;

- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator
      withBoolean:(BOOL)urlSafe;

- (BOOL)isUrlSafe;

- (void)encodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;

- (void)decodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;

+ (BOOL)isArrayByteBase64WithByteArray:(IOSByteArray *)arrayOctet;

+ (BOOL)isBase64WithByte:(char)octet;

+ (BOOL)isBase64WithNSString:(NSString *)base64;

+ (BOOL)isBase64WithByteArray:(IOSByteArray *)arrayOctet;

+ (IOSByteArray *)encodeBase64WithByteArray:(IOSByteArray *)binaryData;

+ (NSString *)encodeBase64StringWithByteArray:(IOSByteArray *)binaryData;

+ (IOSByteArray *)encodeBase64URLSafeWithByteArray:(IOSByteArray *)binaryData;

+ (NSString *)encodeBase64URLSafeStringWithByteArray:(IOSByteArray *)binaryData;

+ (IOSByteArray *)encodeBase64ChunkedWithByteArray:(IOSByteArray *)binaryData;

+ (IOSByteArray *)encodeBase64WithByteArray:(IOSByteArray *)binaryData
                                withBoolean:(BOOL)isChunked;

+ (IOSByteArray *)encodeBase64WithByteArray:(IOSByteArray *)binaryData
                                withBoolean:(BOOL)isChunked
                                withBoolean:(BOOL)urlSafe;

+ (IOSByteArray *)encodeBase64WithByteArray:(IOSByteArray *)binaryData
                                withBoolean:(BOOL)isChunked
                                withBoolean:(BOOL)urlSafe
                                    withInt:(int)maxResultSize;

+ (IOSByteArray *)decodeBase64WithNSString:(NSString *)base64String;

+ (IOSByteArray *)decodeBase64WithByteArray:(IOSByteArray *)base64Data;

+ (JavaMathBigInteger *)decodeIntegerWithByteArray:(IOSByteArray *)pArray;

+ (IOSByteArray *)encodeIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)bigInt;

+ (IOSByteArray *)toIntegerBytesWithJavaMathBigInteger:(JavaMathBigInteger *)bigInt;

- (BOOL)isInAlphabetWithByte:(char)octet;

- (void)copyAllFieldsTo:(KTUtilBase64 *)other;

@end

FOUNDATION_EXPORT BOOL KTUtilBase64_initialized;
J2OBJC_STATIC_INIT(KTUtilBase64)

J2OBJC_FIELD_SETTER(KTUtilBase64, encodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase64, decodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase64, lineSeparator_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, BITS_PER_ENCODED_BYTE, int)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, BYTES_PER_UNENCODED_BLOCK, int)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, BYTES_PER_ENCODED_BLOCK, int)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase64_CHUNK_SEPARATOR_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, CHUNK_SEPARATOR_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase64_STANDARD_ENCODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, STANDARD_ENCODE_TABLE_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase64_URL_SAFE_ENCODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, URL_SAFE_ENCODE_TABLE_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase64_DECODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, DECODE_TABLE_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase64, MASK_6BITS, int)

typedef KTUtilBase64 ComKloudtekUtilBase64;

#endif // _KTUtilBase64_H_
