//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/Base32.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _KTUtilBase32_H_
#define _KTUtilBase32_H_

@class IOSByteArray;
@class KTUtilBaseNCodec_Context;

#import "JreEmulation.h"
#include "BaseNCodec.h"

#define KTUtilBase32_BITS_PER_ENCODED_BYTE 5
#define KTUtilBase32_BYTES_PER_ENCODED_BLOCK 8
#define KTUtilBase32_BYTES_PER_UNENCODED_BLOCK 5
#define KTUtilBase32_MASK_5BITS 31

@interface KTUtilBase32 : KTUtilBaseNCodec {
 @public
  int decodeSize_;
  IOSByteArray *decodeTable_;
  int encodeSize_;
  IOSByteArray *encodeTable_;
  IOSByteArray *lineSeparator_;
}

- (id)init;

- (id)initWithBoolean:(BOOL)useHex;

- (id)initWithInt:(int)lineLength;

- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator;

- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator
      withBoolean:(BOOL)useHex;

- (void)decodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;

- (void)encodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;

- (BOOL)isInAlphabetWithByte:(char)octet;

- (void)copyAllFieldsTo:(KTUtilBase32 *)other;

@end

FOUNDATION_EXPORT BOOL KTUtilBase32_initialized;
J2OBJC_STATIC_INIT(KTUtilBase32)

J2OBJC_FIELD_SETTER(KTUtilBase32, decodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase32, encodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase32, lineSeparator_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, BITS_PER_ENCODED_BYTE, int)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, BYTES_PER_ENCODED_BLOCK, int)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, BYTES_PER_UNENCODED_BLOCK, int)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase32_CHUNK_SEPARATOR_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, CHUNK_SEPARATOR_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase32_DECODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, DECODE_TABLE_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase32_ENCODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, ENCODE_TABLE_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase32_HEX_DECODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, HEX_DECODE_TABLE_, IOSByteArray *)

FOUNDATION_EXPORT IOSByteArray *KTUtilBase32_HEX_ENCODE_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, HEX_ENCODE_TABLE_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(KTUtilBase32, MASK_5BITS, int)

typedef KTUtilBase32 ComKloudtekUtilBase32;

#endif // _KTUtilBase32_H_
