//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/BaseNCodec.java
//
//  Created by yinkaf on 22/04/14.
//

#ifndef _KTUtilBaseNCodec_H_
#define _KTUtilBaseNCodec_H_

@class IOSByteArray;
@class KTUtilBaseNCodec_Context;

#import "JreEmulation.h"

#define KTUtilBaseNCodec_DEFAULT_BUFFER_RESIZE_FACTOR 2
#define KTUtilBaseNCodec_DEFAULT_BUFFER_SIZE 8192
#define KTUtilBaseNCodec_EOF -1
#define KTUtilBaseNCodec_MASK_8BITS 255
#define KTUtilBaseNCodec_MIME_CHUNK_SIZE 76
#define KTUtilBaseNCodec_PAD_DEFAULT 61
#define KTUtilBaseNCodec_PEM_CHUNK_SIZE 64

@interface KTUtilBaseNCodec : NSObject {
 @public
  char PAD_;
  int unencodedBlockSize_;
  int encodedBlockSize_;
  int lineLength_;
  int chunkSeparatorLength_;
}

+ (int)getEOF;
+ (int)MIME_CHUNK_SIZE;
+ (int)PEM_CHUNK_SIZE;
+ (int)DEFAULT_BUFFER_RESIZE_FACTOR;
+ (int)DEFAULT_BUFFER_SIZE;
+ (int)MASK_8BITS;
+ (char)PAD_DEFAULT;
- (id)initWithInt:(int)unencodedBlockSize
          withInt:(int)encodedBlockSize
          withInt:(int)lineLength
          withInt:(int)chunkSeparatorLength;
- (BOOL)hasDataWithKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (int)availableWithKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (int)getDefaultBufferSize;
- (IOSByteArray *)resizeBufferWithKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (IOSByteArray *)ensureBufferSizeWithInt:(int)size
             withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (int)readResultsWithByteArray:(IOSByteArray *)b
                        withInt:(int)bPos
                        withInt:(int)bAvail
   withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
+ (BOOL)isWhiteSpaceWithByte:(char)byteToCheck;
- (id)encodeWithId:(id)obj;
- (NSString *)encodeToStringWithByteArray:(IOSByteArray *)pArray;
- (NSString *)encodeAsStringWithByteArray:(IOSByteArray *)pArray;
- (id)decodeWithId:(id)obj;
- (IOSByteArray *)decodeWithNSString:(NSString *)pArray;
- (IOSByteArray *)decodeWithByteArray:(IOSByteArray *)pArray;
- (IOSByteArray *)encodeWithByteArray:(IOSByteArray *)pArray;
- (void)encodeWithByteArray:(IOSByteArray *)pArray
                    withInt:(int)i
                    withInt:(int)length
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (void)decodeWithByteArray:(IOSByteArray *)pArray
                    withInt:(int)i
                    withInt:(int)length
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (BOOL)isInAlphabetWithByte:(char)value;
- (BOOL)isInAlphabetWithByteArray:(IOSByteArray *)arrayOctet
                      withBoolean:(BOOL)allowWSPad;
- (BOOL)isInAlphabetWithNSString:(NSString *)basen;
- (BOOL)containsAlphabetOrPadWithByteArray:(IOSByteArray *)arrayOctet;
- (long long int)getEncodedLengthWithByteArray:(IOSByteArray *)pArray;
- (void)copyAllFieldsTo:(KTUtilBaseNCodec *)other;
@end

typedef KTUtilBaseNCodec ComKloudtekUtilBaseNCodec;

@interface KTUtilBaseNCodec_Context : NSObject {
 @public
  int ibitWorkArea_;
  long long int lbitWorkArea_;
  IOSByteArray *buffer_;
  int pos_;
  int readPos_;
  BOOL eof_;
  int currentLinePos_;
  int modulus_;
}

- (id)init;
- (NSString *)description;
- (void)copyAllFieldsTo:(KTUtilBaseNCodec_Context *)other;
@end

J2OBJC_FIELD_SETTER(KTUtilBaseNCodec_Context, buffer_, IOSByteArray *)

#endif // _KTUtilBaseNCodec_H_
