//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/Base32.java
//
//  Created by yannick on 08/02/14.
//

#ifndef _KTUtilBase32_H_
#define _KTUtilBase32_H_

@class IOSByteArray;
@class KTUtilBaseNCodec_Context;

#import "JreEmulation.h"
#include "BaseNCodec.h"

#define KTUtilBase32_BITS_PER_ENCODED_BYTE 5
#define KTUtilBase32_BYTES_PER_ENCODED_BLOCK 8
#define KTUtilBase32_BYTES_PER_UNENCODED_BLOCK 5
#define KTUtilBase32_MASK_5BITS 31

@interface KTUtilBase32 : KTUtilBaseNCodec {
 @public
  int decodeSize_;
  IOSByteArray *decodeTable_;
  int encodeSize_;
  IOSByteArray *encodeTable_;
  IOSByteArray *lineSeparator_;
}

+ (IOSByteArray *)CHUNK_SEPARATOR;
+ (IOSByteArray *)DECODE_TABLE;
+ (IOSByteArray *)ENCODE_TABLE;
+ (IOSByteArray *)HEX_DECODE_TABLE;
+ (IOSByteArray *)HEX_ENCODE_TABLE;
- (id)init;
- (id)initWithBoolean:(BOOL)useHex;
- (id)initWithInt:(int)lineLength;
- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator;
- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator
      withBoolean:(BOOL)useHex;
- (void)decodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (void)encodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilBaseNCodec_Context:(KTUtilBaseNCodec_Context *)context;
- (BOOL)isInAlphabetWithByte:(char)octet;
- (void)copyAllFieldsTo:(KTUtilBase32 *)other;
@end

J2OBJC_FIELD_SETTER(KTUtilBase32, decodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase32, encodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilBase32, lineSeparator_, IOSByteArray *)

typedef KTUtilBase32 ComKloudtekUtilBase32;

#endif // _KTUtilBase32_H_
