//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/Base32.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _KTUtilsBase32_H_
#define _KTUtilsBase32_H_

@class IOSByteArray;
@class KTUtilsBaseNCodec_Context;

#import "JreEmulation.h"
#include "BaseNCodec.h"

#define KTUtilsBase32_BITS_PER_ENCODED_BYTE 5
#define KTUtilsBase32_BYTES_PER_ENCODED_BLOCK 8
#define KTUtilsBase32_BYTES_PER_UNENCODED_BLOCK 5
#define KTUtilsBase32_MASK_5BITS 31

@interface KTUtilsBase32 : KTUtilsBaseNCodec {
 @public
  int decodeSize_;
  IOSByteArray *decodeTable_;
  int encodeSize_;
  IOSByteArray *encodeTable_;
  IOSByteArray *lineSeparator_;
}

+ (IOSByteArray *)CHUNK_SEPARATOR;
+ (IOSByteArray *)DECODE_TABLE;
+ (IOSByteArray *)ENCODE_TABLE;
+ (IOSByteArray *)HEX_DECODE_TABLE;
+ (IOSByteArray *)HEX_ENCODE_TABLE;
- (id)init;
- (id)initWithBoolean:(BOOL)useHex;
- (id)initWithInt:(int)lineLength;
- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator;
- (id)initWithInt:(int)lineLength
    withByteArray:(IOSByteArray *)lineSeparator
      withBoolean:(BOOL)useHex;
- (void)decodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (void)encodeWithByteArray:(IOSByteArray *)inArg
                    withInt:(int)inPos
                    withInt:(int)inAvail
withKTUtilsBaseNCodec_Context:(KTUtilsBaseNCodec_Context *)context;
- (BOOL)isInAlphabetWithByte:(char)octet;
- (void)copyAllFieldsTo:(KTUtilsBase32 *)other;
@end

J2OBJC_FIELD_SETTER(KTUtilsBase32, decodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilsBase32, encodeTable_, IOSByteArray *)
J2OBJC_FIELD_SETTER(KTUtilsBase32, lineSeparator_, IOSByteArray *)

typedef KTUtilsBase32 ComKloudtekUtilBase32;

#endif // _KTUtilsBase32_H_
