//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/io/ByteArrayDataOutputStream.java
//
//  Created by yinkaf on 6/14/14.
//

#include "ByteArrayDataOutputStream.h"
#include "IOSPrimitiveArray.h"
#include "java/io/ByteArrayOutputStream.h"

@implementation KTUtilByteArrayDataOutputStream

- (id)init {
  return [super initWithJavaIoOutputStream:[[JavaIoByteArrayOutputStream alloc] init]];
}

- (id)initWithInt:(int)size {
  return [super initWithJavaIoOutputStream:[[JavaIoByteArrayOutputStream alloc] initWithInt:size]];
}

- (IOSByteArray *)toByteArray {
  return [((JavaIoByteArrayOutputStream *) nil_chk(((JavaIoByteArrayOutputStream *) check_class_cast(out_, [JavaIoByteArrayOutputStream class])))) toByteArray];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "ByteArrayDataOutputStream", NULL, 0x1, NULL },
    { "initWithInt:", "ByteArrayDataOutputStream", NULL, 0x1, NULL },
    { "toByteArray", NULL, "[B", 0x1, NULL },
  };
  static J2ObjcClassInfo _KTUtilByteArrayDataOutputStream = { "ByteArrayDataOutputStream", "com.kloudtek.util.io", NULL, 0x1, 3, methods, 0, NULL, 0, NULL};
  return &_KTUtilByteArrayDataOutputStream;
}

@end
