//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/io/ByteArrayDataInputStream.java
//
//  Created by yinkaf on 6/11/14.
//

#include "ByteArrayDataInputStream.h"
#include "IOSPrimitiveArray.h"
#include "java/io/ByteArrayInputStream.h"

@implementation KTUtilByteArrayDataInputStream

- (id)initWithByteArray:(IOSByteArray *)buf {
  return [super initWithJavaIoInputStream:[[JavaIoByteArrayInputStream alloc] initWithByteArray:buf]];
}

- (id)initWithByteArray:(IOSByteArray *)buf
                withInt:(int)offset
                withInt:(int)length {
  return [super initWithJavaIoInputStream:[[JavaIoByteArrayInputStream alloc] initWithByteArray:buf withInt:offset withInt:length]];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithByteArray:", "ByteArrayDataInputStream", NULL, 0x1, NULL },
    { "initWithByteArray:withInt:withInt:", "ByteArrayDataInputStream", NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _KTUtilByteArrayDataInputStream = { "ByteArrayDataInputStream", "com.kloudtek.util.io", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_KTUtilByteArrayDataInputStream;
}

@end
