//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/ByteArrayDataInputStream.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _KTUtilsByteArrayDataInputStream_H_
#define _KTUtilsByteArrayDataInputStream_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "DataInputStream.h"

@interface KTUtilsByteArrayDataInputStream : KTUtilsDataInputStream {
}

- (id)initWithByteArray:(IOSByteArray *)buf;
- (id)initWithByteArray:(IOSByteArray *)buf
                withInt:(int)offset
                withInt:(int)length;
@end

typedef KTUtilsByteArrayDataInputStream ComKloudtekUtilIoByteArrayDataInputStream;

#endif // _KTUtilsByteArrayDataInputStream_H_
