//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/crypto/CryptoUtils.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _ComKloudtekUtilCryptoCryptoUtils_H_
#define _ComKloudtekUtilCryptoCryptoUtils_H_

@class IOSByteArray;
@class IOSObjectArray;
@class JavaNioByteBuffer;
@class JavaNioCharBuffer;
@class JavaSecuritySecureRandom;
@class JavaUtilLoggingLogger;
@protocol JavaSecurityKey;
@protocol JavaUtilCollection;

#import "JreEmulation.h"

@interface ComKloudtekUtilCryptoCryptoUtils : NSObject {
}

+ (IOSObjectArray *)splitKeyWithByteArray:(IOSByteArray *)key
                                  withInt:(int)amount;

+ (void)zeroWithCharArray2:(IOSObjectArray *)data;

+ (void)zeroWithByteArray2:(IOSObjectArray *)data;

+ (void)zeroWithJavaNioCharBuffer:(JavaNioCharBuffer *)data;

+ (void)zeroWithJavaNioByteBuffer:(JavaNioByteBuffer *)data;

+ (IOSByteArray *)mergeSplitKeyWithByteArray2:(IOSObjectArray *)keys;

+ (IOSByteArray *)mergeSplitKeyWithJavaUtilCollection:(id<JavaUtilCollection>)keys;

+ (IOSByteArray *)xor__WithByteArray:(IOSByteArray *)b1
                       withByteArray:(IOSByteArray *)b2;

+ (JavaSecuritySecureRandom *)rng;

+ (void)destroyWithJavaSecurityKey:(id<JavaSecurityKey>)key;

- (id)init;

@end

FOUNDATION_EXPORT BOOL ComKloudtekUtilCryptoCryptoUtils_initialized;
J2OBJC_STATIC_INIT(ComKloudtekUtilCryptoCryptoUtils)

FOUNDATION_EXPORT JavaUtilLoggingLogger *ComKloudtekUtilCryptoCryptoUtils_logger_;
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoCryptoUtils, logger_, JavaUtilLoggingLogger *)

FOUNDATION_EXPORT JavaSecuritySecureRandom *ComKloudtekUtilCryptoCryptoUtils_rng__;
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoCryptoUtils, rng__, JavaSecuritySecureRandom *)

#endif // _ComKloudtekUtilCryptoCryptoUtils_H_
