//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataInputStream.java
//
//  Created by yannick on 28/12/13.
//

#ifndef _KTUtilsDataInputStream_H_
#define _KTUtilsDataInputStream_H_

@class IOSByteArray;
@class JavaIoInputStream;

#import "JreEmulation.h"
#include "java/io/DataInputStream.h"

@interface KTUtilsDataInputStream : JavaIoDataInputStream {
}

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (NSString *)readString;
- (IOSByteArray *)readData;
@end

typedef KTUtilsDataInputStream ComKloudtekUtilIoDataInputStream;

#endif // _KTUtilsDataInputStream_H_
