//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/io/DataOutputStream.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _KTUtilDataOutputStream_H_
#define _KTUtilDataOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;
@class JavaLangEnum;
@class JavaUtilUUID;
@protocol JavaIoDataOutput;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/io/DataOutputStream.h"

@interface KTUtilDataOutputStream : JavaIoDataOutputStream {
}

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

- (void)writeStringWithNSString:(NSString *)str;

- (void)writeDataWithByteArray:(IOSByteArray *)data;

- (void)writeUUIDWithJavaUtilUUID:(JavaUtilUUID *)uuid;

- (void)writeByteEnumWithJavaLangEnum:(JavaLangEnum *)enumeration;

- (void)writeShortEnumWithJavaLangEnum:(JavaLangEnum *)enumeration;

- (void)writeIntEnumWithJavaLangEnum:(JavaLangEnum *)enumeration;

- (void)writeLongListWithJavaUtilList:(id<JavaUtilList>)list;

- (void)writeIntListWithJavaUtilList:(id<JavaUtilList>)list;

- (void)writeUUIDListWithJavaUtilList:(id<JavaUtilList>)list;

- (void)writeUTFListWithJavaUtilList:(id<JavaUtilList>)list;

+ (void)writeStringWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                           withNSString:(NSString *)str;

+ (void)writeDataWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                        withByteArray:(IOSByteArray *)data;

+ (void)writeUUIDWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                     withJavaUtilUUID:(JavaUtilUUID *)uuid;

+ (void)writeByteEnumWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                         withJavaLangEnum:(JavaLangEnum *)enumeration;

+ (void)writeShortEnumWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                          withJavaLangEnum:(JavaLangEnum *)enumeration;

+ (void)writeIntEnumWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                        withJavaLangEnum:(JavaLangEnum *)enumeration;

+ (int)enumValueWithJavaLangEnum:(JavaLangEnum *)enumeration;

@end

__attribute__((always_inline)) inline void KTUtilDataOutputStream_init() {}

typedef KTUtilDataOutputStream ComKloudtekUtilIoDataOutputStream;

#endif // _KTUtilDataOutputStream_H_
