//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataInputStream.java
//
//  Created by yannick on 03/02/14.
//

#ifndef _KTUtilDataInputStream_H_
#define _KTUtilDataInputStream_H_

@class IOSByteArray;
@class JavaIoInputStream;
@protocol JavaIoDataInput;

#import "JreEmulation.h"
#include "java/io/DataInputStream.h"

@interface KTUtilDataInputStream : JavaIoDataInputStream {
}

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (NSString *)readString;
- (IOSByteArray *)readData;
+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
@end

typedef KTUtilDataInputStream ComKloudtekUtilIoDataInputStream;

#endif // _KTUtilDataInputStream_H_
