//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataInputStream.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _KTUtilsDataInputStream_H_
#define _KTUtilsDataInputStream_H_

@class IOSByteArray;
@class JavaIoInputStream;
@protocol JavaIoDataInput;

#import "JreEmulation.h"
#include "java/io/DataInputStream.h"

@interface KTUtilsDataInputStream : JavaIoDataInputStream {
}

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (NSString *)readString;
- (IOSByteArray *)readData;
+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
@end

typedef KTUtilsDataInputStream ComKloudtekUtilIoDataInputStream;

#endif // _KTUtilsDataInputStream_H_
