//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataInputStream.java
//
//  Created by yannick on 06/01/14.
//

#include "DataInputStream.h"
#include "IOSByteArray.h"
#include "IOSClass.h"
#include "java/io/DataInput.h"
#include "java/io/DataInputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"

@implementation KTUtilsDataInputStream

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  return [super initWithJavaIoInputStream:inArg];
}

- (NSString *)readString {
  return [KTUtilsDataInputStream readStringWithJavaIoDataInput:self];
}

- (IOSByteArray *)readData {
  return [KTUtilsDataInputStream readDataWithJavaIoDataInput:self];
}

+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  if ([((id<JavaIoDataInput>) nil_chk(inArg)) readBoolean]) {
    return [inArg readUTF];
  }
  else {
    return nil;
  }
}

+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int len = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  if (len > 0) {
    IOSByteArray *data = [IOSByteArray arrayWithLength:len];
    [inArg readFullyWithByteArray:data];
    return data;
  }
  else if (len == 0) {
    return [IOSByteArray arrayWithLength:0];
  }
  else {
    return nil;
  }
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "readString", NULL, "LNSString", 0x1, "JavaIoIOException" },
    { "readData", NULL, "LIOSByteArray", 0x1, "JavaIoIOException" },
    { "readStringWithJavaIoDataInput:", NULL, "LNSString", 0x9, "JavaIoIOException" },
    { "readDataWithJavaIoDataInput:", NULL, "LIOSByteArray", 0x9, "JavaIoIOException" },
  };
  static J2ObjcClassInfo _KTUtilsDataInputStream = { "DataInputStream", "com.kloudtek.util.io", NULL, 0x1, 4, methods, 0, NULL, 0, NULL};
  return &_KTUtilsDataInputStream;
}

@end
