//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/io/DataInputStream.java
//
//  Created by yinkaf on 6/11/14.
//

#include "DataInputStream.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "java/io/DataInput.h"
#include "java/io/DataInputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/lang/ArrayIndexOutOfBoundsException.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "java/util/UUID.h"

@implementation KTUtilDataInputStream

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  return [super initWithJavaIoInputStream:inArg];
}

- (NSString *)readString {
  return [KTUtilDataInputStream readStringWithJavaIoDataInput:self];
}

- (JavaUtilUUID *)readUUID {
  return [KTUtilDataInputStream readUUIDWithJavaIoDataInput:self];
}

- (IOSByteArray *)readData {
  return [KTUtilDataInputStream readDataWithJavaIoDataInput:self];
}

- (id<JavaUtilList>)readLongList {
  return [KTUtilDataInputStream readLongListWithJavaIoDataInput:self];
}

- (id<JavaUtilList>)readUUIDList {
  return [KTUtilDataInputStream readUUIDListWithJavaIoDataInput:self];
}

- (id<JavaUtilList>)readIntList {
  return [KTUtilDataInputStream readIntListWithJavaIoDataInput:self];
}

- (id<JavaUtilList>)readUTFList {
  return [KTUtilDataInputStream readUTFListWithJavaIoDataInput:self];
}

- (id)readByteEnumWithIOSClass:(IOSClass *)enumClass {
  return [KTUtilDataInputStream readByteEnumWithIOSClass:enumClass withJavaIoDataInput:self];
}

- (id)readShortEnumWithIOSClass:(IOSClass *)enumClass {
  return [KTUtilDataInputStream readShortEnumWithIOSClass:enumClass withJavaIoDataInput:self];
}

- (id)readIntEnumWithIOSClass:(IOSClass *)enumClass {
  return [KTUtilDataInputStream readIntEnumWithIOSClass:enumClass withJavaIoDataInput:self];
}

+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  if ([((id<JavaIoDataInput>) nil_chk(inArg)) readBoolean]) {
    return [inArg readUTF];
  }
  else {
    return nil;
  }
}

+ (JavaUtilUUID *)readUUIDWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  return [[JavaUtilUUID alloc] initWithLong:[((id<JavaIoDataInput>) nil_chk(inArg)) readLong] withLong:[inArg readLong]];
}

+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int len = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  if (len > 0) {
    IOSByteArray *data = [IOSByteArray arrayWithLength:len];
    [inArg readFullyWithByteArray:data];
    return data;
  }
  else if (len == 0) {
    return [IOSByteArray arrayWithLength:0];
  }
  else {
    return nil;
  }
}

+ (id<JavaUtilList>)readLongListWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int nb = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  JavaUtilArrayList *list = [[JavaUtilArrayList alloc] initWithInt:nb];
  for (int i = 0; i < nb; i++) {
    [list addWithId:[JavaLangLong valueOfWithLong:[inArg readLong]]];
  }
  return list;
}

+ (id<JavaUtilList>)readUUIDListWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int nb = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  JavaUtilArrayList *list = [[JavaUtilArrayList alloc] initWithInt:nb];
  for (int i = 0; i < nb; i++) {
    [list addWithId:[[JavaUtilUUID alloc] initWithLong:[inArg readLong] withLong:[inArg readLong]]];
  }
  return list;
}

+ (id<JavaUtilList>)readIntListWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int nb = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  JavaUtilArrayList *list = [[JavaUtilArrayList alloc] initWithInt:nb];
  for (int i = 0; i < nb; i++) {
    [list addWithId:[JavaLangInteger valueOfWithInt:[inArg readInt]]];
  }
  return list;
}

+ (id<JavaUtilList>)readUTFListWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int nb = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  JavaUtilArrayList *list = [[JavaUtilArrayList alloc] initWithInt:nb];
  for (int i = 0; i < nb; i++) {
    [list addWithId:[inArg readUTF]];
  }
  return list;
}

+ (id)readByteEnumWithIOSClass:(IOSClass *)enumClass
           withJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  return [KTUtilDataInputStream readEnumWithIOSClass:enumClass withInt:[((id<JavaIoDataInput>) nil_chk(inArg)) readByte]];
}

+ (id)readShortEnumWithIOSClass:(IOSClass *)enumClass
            withJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  return [KTUtilDataInputStream readEnumWithIOSClass:enumClass withInt:[((id<JavaIoDataInput>) nil_chk(inArg)) readShort]];
}

+ (id)readIntEnumWithIOSClass:(IOSClass *)enumClass
          withJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  return [KTUtilDataInputStream readEnumWithIOSClass:enumClass withInt:[((id<JavaIoDataInput>) nil_chk(inArg)) readInt]];
}

+ (id)readEnumWithIOSClass:(IOSClass *)enumClass
                   withInt:(int)idx {
  @try {
    return idx == -1 ? nil : IOSObjectArray_Get(nil_chk([((IOSClass *) nil_chk(enumClass)) getEnumConstants]), idx);
  }
  @catch (JavaLangArrayIndexOutOfBoundsException *e) {
    @throw [[JavaIoIOException alloc] initWithNSString:@"Invalid enum value"];
  }
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoInputStream:", "DataInputStream", NULL, 0x1, NULL },
    { "readString", NULL, "Ljava.lang.String;", 0x1, "Ljava.io.IOException;" },
    { "readUUID", NULL, "Ljava.util.UUID;", 0x1, "Ljava.io.IOException;" },
    { "readData", NULL, "[B", 0x1, "Ljava.io.IOException;" },
    { "readLongList", NULL, "Ljava.util.List;", 0x1, "Ljava.io.IOException;" },
    { "readUUIDList", NULL, "Ljava.util.List;", 0x1, "Ljava.io.IOException;" },
    { "readIntList", NULL, "Ljava.util.List;", 0x1, "Ljava.io.IOException;" },
    { "readUTFList", NULL, "Ljava.util.List;", 0x1, "Ljava.io.IOException;" },
    { "readByteEnumWithIOSClass:", "readByteEnum", "TX;", 0x1, "Ljava.io.IOException;" },
    { "readShortEnumWithIOSClass:", "readShortEnum", "TX;", 0x1, "Ljava.io.IOException;" },
    { "readIntEnumWithIOSClass:", "readIntEnum", "TX;", 0x1, "Ljava.io.IOException;" },
    { "readStringWithJavaIoDataInput:", "readString", "Ljava.lang.String;", 0x9, "Ljava.io.IOException;" },
    { "readUUIDWithJavaIoDataInput:", "readUUID", "Ljava.util.UUID;", 0x9, "Ljava.io.IOException;" },
    { "readDataWithJavaIoDataInput:", "readData", "[B", 0x9, "Ljava.io.IOException;" },
    { "readLongListWithJavaIoDataInput:", "readLongList", "Ljava.util.List;", 0x9, "Ljava.io.IOException;" },
    { "readUUIDListWithJavaIoDataInput:", "readUUIDList", "Ljava.util.List;", 0x9, "Ljava.io.IOException;" },
    { "readIntListWithJavaIoDataInput:", "readIntList", "Ljava.util.List;", 0x9, "Ljava.io.IOException;" },
    { "readUTFListWithJavaIoDataInput:", "readUTFList", "Ljava.util.List;", 0x9, "Ljava.io.IOException;" },
    { "readByteEnumWithIOSClass:withJavaIoDataInput:", "readByteEnum", "TX;", 0x9, "Ljava.io.IOException;" },
    { "readShortEnumWithIOSClass:withJavaIoDataInput:", "readShortEnum", "TX;", 0x9, "Ljava.io.IOException;" },
    { "readIntEnumWithIOSClass:withJavaIoDataInput:", "readIntEnum", "TX;", 0x9, "Ljava.io.IOException;" },
    { "readEnumWithIOSClass:withInt:", "readEnum", "TX;", 0xa, "Ljava.io.IOException;" },
  };
  static J2ObjcClassInfo _KTUtilDataInputStream = { "DataInputStream", "com.kloudtek.util.io", NULL, 0x1, 22, methods, 0, NULL, 0, NULL};
  return &_KTUtilDataInputStream;
}

@end
