//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataInputStream.java
//
//  Created by yinkaf on 22/04/14.
//

#include "DataInputStream.h"
#include "IOSByteArray.h"
#include "IOSClass.h"
#include "java/io/DataInput.h"
#include "java/io/DataInputStream.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"

@implementation KTUtilDataInputStream

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  return [super initWithJavaIoInputStream:inArg];
}

- (NSString *)readString {
  return [KTUtilDataInputStream readStringWithJavaIoDataInput:self];
}

- (IOSByteArray *)readData {
  return [KTUtilDataInputStream readDataWithJavaIoDataInput:self];
}

+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  if ([((id<JavaIoDataInput>) nil_chk(inArg)) readBoolean]) {
    return [inArg readUTF];
  }
  else {
    return nil;
  }
}

+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg {
  int len = [((id<JavaIoDataInput>) nil_chk(inArg)) readInt];
  if (len > 0) {
    IOSByteArray *data = [IOSByteArray arrayWithLength:len];
    [inArg readFullyWithByteArray:data];
    return data;
  }
  else if (len == 0) {
    return [IOSByteArray arrayWithLength:0];
  }
  else {
    return nil;
  }
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoInputStream:", "DataInputStream", NULL, 0x1, NULL },
    { "readString", NULL, "Ljava.lang.String;", 0x1, "Ljava.io.IOException;" },
    { "readData", NULL, "[B", 0x1, "Ljava.io.IOException;" },
    { "readStringWithJavaIoDataInput:", "readString", "Ljava.lang.String;", 0x9, "Ljava.io.IOException;" },
    { "readDataWithJavaIoDataInput:", "readData", "[B", 0x9, "Ljava.io.IOException;" },
  };
  static J2ObjcClassInfo _KTUtilDataInputStream = { "DataInputStream", "com.kloudtek.util.io", NULL, 0x1, 5, methods, 0, NULL, 0, NULL};
  return &_KTUtilDataInputStream;
}

@end
