//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataOutputStream.java
//
//  Created by yannick on 28/12/13.
//

#include "DataOutputStream.h"
#include "IOSByteArray.h"
#include "IOSClass.h"
#include "IOUtils.h"
#include "java/io/DataOutputStream.h"
#include "java/io/IOException.h"
#include "java/io/OutputStream.h"

@implementation KTUtilsDataOutputStream

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg {
  return [super initWithJavaIoOutputStream:outArg];
}

- (void)writeStringWithNSString:(NSString *)str {
  [KTUtilsIOUtils writeStringWithJavaIoDataOutput:self withNSString:str];
}

- (void)writeDataWithByteArray:(IOSByteArray *)data {
  [KTUtilsIOUtils writeDataWithJavaIoDataOutput:self withByteArray:data];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "writeStringWithNSString:", NULL, "V", 0x1, "JavaIoIOException" },
    { "writeDataWithByteArray:", NULL, "V", 0x1, "JavaIoIOException" },
  };
  static J2ObjcClassInfo _KTUtilsDataOutputStream = { "DataOutputStream", "com.kloudtek.util.io", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_KTUtilsDataOutputStream;
}

@end
