//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataOutputStream.java
//
//  Created by yannick on 28/12/13.
//

#ifndef _KTUtilsDataOutputStream_H_
#define _KTUtilsDataOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;

#import "JreEmulation.h"
#include "java/io/DataOutputStream.h"

@interface KTUtilsDataOutputStream : JavaIoDataOutputStream {
}

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (void)writeStringWithNSString:(NSString *)str;
- (void)writeDataWithByteArray:(IOSByteArray *)data;
@end

typedef KTUtilsDataOutputStream ComKloudtekUtilIoDataOutputStream;

#endif // _KTUtilsDataOutputStream_H_
