//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/DataOutputStream.java
//
//  Created by yinkaf on 22/04/14.
//

#ifndef _KTUtilDataOutputStream_H_
#define _KTUtilDataOutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;
@protocol JavaIoDataOutput;

#import "JreEmulation.h"
#include "java/io/DataOutputStream.h"

@interface KTUtilDataOutputStream : JavaIoDataOutputStream {
}

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (void)writeStringWithNSString:(NSString *)str;
- (void)writeDataWithByteArray:(IOSByteArray *)data;
+ (void)writeStringWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                           withNSString:(NSString *)str;
+ (void)writeDataWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                        withByteArray:(IOSByteArray *)data;
@end

typedef KTUtilDataOutputStream ComKloudtekUtilIoDataOutputStream;

#endif // _KTUtilDataOutputStream_H_
