//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/DestroyFailedException.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _JavaxSecurityAuthDestroyFailedException_H_
#define _JavaxSecurityAuthDestroyFailedException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaxSecurityAuthDestroyFailedException_serialVersionUID -7790152857282749162LL

@interface JavaxSecurityAuthDestroyFailedException : JavaLangException {
}

- (id)init;

- (id)initWithNSString:(NSString *)msg;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthDestroyFailedException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityAuthDestroyFailedException, serialVersionUID, long long int)

#endif // _JavaxSecurityAuthDestroyFailedException_H_
