//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/DestroyFailedException.java
//
//  Created by yinkaf on 6/11/14.
//

#include "DestroyFailedException.h"

@implementation JavaxSecurityAuthDestroyFailedException

- (id)init {
  return [super init];
}

- (id)initWithNSString:(NSString *)msg {
  return [super initWithNSString:msg];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "DestroyFailedException", NULL, 0x1, NULL },
    { "initWithNSString:", "DestroyFailedException", NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_DestroyFailedException_", "serialVersionUID", 0x1a, "J", NULL, .constantValue.asLong = JavaxSecurityAuthDestroyFailedException_serialVersionUID },
  };
  static J2ObjcClassInfo _JavaxSecurityAuthDestroyFailedException = { "DestroyFailedException", "javax.security.auth", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_JavaxSecurityAuthDestroyFailedException;
}

@end
