//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/Destroyable.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _JavaxSecurityAuthDestroyable_H_
#define _JavaxSecurityAuthDestroyable_H_

#import "JreEmulation.h"

@protocol JavaxSecurityAuthDestroyable < NSObject, JavaObject >

- (void)destroy;

- (BOOL)isDestroyed;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthDestroyable_init() {}

#endif // _JavaxSecurityAuthDestroyable_H_
