//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/Destroyable.java
//
//  Created by yinkaf on 6/11/14.
//

#include "IOSClass.h"
#include "DestroyFailedException.h"
#include "Destroyable.h"

@interface JavaxSecurityAuthDestroyable : NSObject
@end

@implementation JavaxSecurityAuthDestroyable

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "destroy", NULL, "V", 0x401, "Ljavax.security.auth.DestroyFailedException;" },
    { "isDestroyed", NULL, "Z", 0x401, NULL },
  };
  static J2ObjcClassInfo _JavaxSecurityAuthDestroyable = { "Destroyable", "javax.security.auth", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_JavaxSecurityAuthDestroyable;
}

@end
