//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/crypto/DigestUtils.java
//
//  Created by yinkaf on 6/14/14.
//

#ifndef _ComKloudtekUtilCryptoDigestUtils_H_
#define _ComKloudtekUtilCryptoDigestUtils_H_

@class ComKloudtekUtilCryptoDigestAlgorithmEnum;
@class IOSByteArray;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaSecurityMessageDigest;
@class JavaSecuritySecureRandom;
@class JavaUtilLoggingLogger;

#import "JreEmulation.h"

#define ComKloudtekUtilCryptoDigestUtils_BUFSZ 8192

@interface ComKloudtekUtilCryptoDigestUtils : NSObject {
}

+ (JavaSecurityMessageDigest *)digestWithComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)digestWithByteArray:(IOSByteArray *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)digestWithJavaIoFile:(JavaIoFile *)file
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)digestWithJavaIoInputStream:(JavaIoInputStream *)inputStream
 withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)digestWithJavaIoInputStream:(JavaIoInputStream *)inputStream
                                 withNSString:(NSString *)alg;

+ (IOSByteArray *)saltedDigestWithByteArray:(IOSByteArray *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)saltedDigestWithByteArray:(IOSByteArray *)salt
                              withByteArray:(IOSByteArray *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)saltedDigestWithByteArray:(IOSByteArray *)salt
                              withByteArray:(IOSByteArray *)data
                               withNSString:(NSString *)alg
                                    withInt:(int)hashLen;

+ (BOOL)compareSaltedDigestWithByteArray:(IOSByteArray *)digest
                           withByteArray:(IOSByteArray *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (BOOL)compareSaltedDigestWithNSString:(NSString *)b64Digest
                           withNSString:(NSString *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)generateSalt;

+ (IOSByteArray *)saltedDigestWithNSString:(NSString *)text
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (NSString *)saltedB64DigestWithNSString:(NSString *)text
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (NSString *)saltedB64DigestWithByteArray:(IOSByteArray *)data
withComKloudtekUtilCryptoDigestAlgorithmEnum:(ComKloudtekUtilCryptoDigestAlgorithmEnum *)alg;

+ (IOSByteArray *)sha1WithByteArray:(IOSByteArray *)data;

+ (IOSByteArray *)sha1WithJavaIoInputStream:(JavaIoInputStream *)data;

+ (IOSByteArray *)sha1WithJavaIoFile:(JavaIoFile *)file;

+ (IOSByteArray *)sha256WithByteArray:(IOSByteArray *)data;

+ (IOSByteArray *)sha256WithJavaIoInputStream:(JavaIoInputStream *)data;

+ (IOSByteArray *)sha256WithJavaIoFile:(JavaIoFile *)file;

+ (IOSByteArray *)sha512WithByteArray:(IOSByteArray *)data;

+ (IOSByteArray *)sha512WithJavaIoInputStream:(JavaIoInputStream *)data;

+ (IOSByteArray *)sha512WithJavaIoFile:(JavaIoFile *)file;

+ (IOSByteArray *)md5WithByteArray:(IOSByteArray *)data;

+ (IOSByteArray *)md5WithJavaIoInputStream:(JavaIoInputStream *)data;

+ (IOSByteArray *)md5WithJavaIoFile:(JavaIoFile *)file;

- (id)init;

@end

FOUNDATION_EXPORT BOOL ComKloudtekUtilCryptoDigestUtils_initialized;
J2OBJC_STATIC_INIT(ComKloudtekUtilCryptoDigestUtils)

FOUNDATION_EXPORT JavaUtilLoggingLogger *ComKloudtekUtilCryptoDigestUtils_logger_;
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoDigestUtils, logger_, JavaUtilLoggingLogger *)

FOUNDATION_EXPORT JavaSecuritySecureRandom *ComKloudtekUtilCryptoDigestUtils_random_;
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoDigestUtils, random_, JavaSecuritySecureRandom *)

J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoDigestUtils, BUFSZ, int)

#endif // _ComKloudtekUtilCryptoDigestUtils_H_
