//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/IOUtils.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _KTUtilsIOUtils_H_
#define _KTUtilsIOUtils_H_

@class IOSByteArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;

#import "JreEmulation.h"

#define KTUtilsIOUtils_DEF_BUFF_SIZE 10240

@interface KTUtilsIOUtils : NSObject {
}

+ (IOSByteArray *)toByteArrayWithJavaIoInputStream:(JavaIoInputStream *)inputStream;
+ (long long int)copy__WithJavaIoInputStream:(JavaIoInputStream *)inputStream
                      withJavaIoOutputStream:(JavaIoOutputStream *)outputStream OBJC_METHOD_FAMILY_NONE;
+ (long long int)copy__WithJavaIoInputStream:(JavaIoInputStream *)inputStream
                      withJavaIoOutputStream:(JavaIoOutputStream *)outputStream
                                     withInt:(int)bufSize OBJC_METHOD_FAMILY_NONE;
- (id)init;
@end

typedef KTUtilsIOUtils ComKloudtekUtilIoIOUtils;

#endif // _KTUtilsIOUtils_H_
