//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/IOUtils.java
//
//  Created by yannick on 06/01/14.
//

#include "ByteArrayDataOutputStream.h"
#include "IOSByteArray.h"
#include "IOSClass.h"
#include "IOUtils.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/io/OutputStream.h"

@implementation KTUtilsIOUtils

+ (IOSByteArray *)toByteArrayWithJavaIoInputStream:(JavaIoInputStream *)inputStream {
  KTUtilsByteArrayDataOutputStream *buffer = [[KTUtilsByteArrayDataOutputStream alloc] init];
  [KTUtilsIOUtils copy__WithJavaIoInputStream:inputStream withJavaIoOutputStream:buffer];
  [buffer close];
  return [buffer toByteArray];
}

+ (long long int)copy__WithJavaIoInputStream:(JavaIoInputStream *)inputStream
                      withJavaIoOutputStream:(JavaIoOutputStream *)outputStream {
  return [KTUtilsIOUtils copy__WithJavaIoInputStream:inputStream withJavaIoOutputStream:outputStream withInt:KTUtilsIOUtils_DEF_BUFF_SIZE];
}

+ (long long int)copy__WithJavaIoInputStream:(JavaIoInputStream *)inputStream
                      withJavaIoOutputStream:(JavaIoOutputStream *)outputStream
                                     withInt:(int)bufSize {
  IOSByteArray *buffer = [IOSByteArray arrayWithLength:bufSize];
  long long int count = 0;
  while (YES) {
    int read = [((JavaIoInputStream *) nil_chk(inputStream)) readWithByteArray:buffer];
    if (read > 0) {
      [((JavaIoOutputStream *) nil_chk(outputStream)) writeWithByteArray:buffer withInt:0 withInt:read];
      count += read;
    }
    else {
      return count;
    }
  }
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "toByteArrayWithJavaIoInputStream:", NULL, "LIOSByteArray", 0x9, "JavaIoIOException" },
    { "copy__WithJavaIoInputStream:withJavaIoOutputStream:", NULL, "J", 0x9, "JavaIoIOException" },
    { "copy__WithJavaIoInputStream:withJavaIoOutputStream:withInt:", NULL, "J", 0xa, "JavaIoIOException" },
  };
  static J2ObjcFieldInfo fields[] = {
    { "DEF_BUFF_SIZE_", NULL, 0x1a, "I" },
  };
  static J2ObjcClassInfo _KTUtilsIOUtils = { "IOUtils", "com.kloudtek.util.io", NULL, 0x1, 3, methods, 1, fields, 0, NULL};
  return &_KTUtilsIOUtils;
}

@end
