//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/io/IOUtils.java
//
//  Created by yannick on 28/12/13.
//

#ifndef _KTUtilsIOUtils_H_
#define _KTUtilsIOUtils_H_

@class IOSByteArray;
@protocol JavaIoDataInput;
@protocol JavaIoDataOutput;

#import "JreEmulation.h"

@interface KTUtilsIOUtils : NSObject {
}

+ (void)writeStringWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                           withNSString:(NSString *)str;
+ (NSString *)readStringWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
+ (void)writeDataWithJavaIoDataOutput:(id<JavaIoDataOutput>)outArg
                        withByteArray:(IOSByteArray *)data;
+ (IOSByteArray *)readDataWithJavaIoDataInput:(id<JavaIoDataInput>)inArg;
- (id)init;
@end

typedef KTUtilsIOUtils ComKloudtekUtilIoIOUtils;

#endif // _KTUtilsIOUtils_H_
