//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/crypto/SymmetricAlgorithm.java
//
//  Created by yinkaf on 6/14/14.
//

#include "IOSClass.h"
#include "SymmetricAlgorithm.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

BOOL ComKloudtekUtilCryptoSymmetricAlgorithmEnum_initialized = NO;

ComKloudtekUtilCryptoSymmetricAlgorithmEnum *ComKloudtekUtilCryptoSymmetricAlgorithmEnum_values[1];

@implementation ComKloudtekUtilCryptoSymmetricAlgorithmEnum

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal {
  if ((self = [super initWithNSString:__name withInt:__ordinal])) {
    jceId_ = [self name];
  }
  return self;
}

- (id)initWithNSString:(NSString *)jceId
          withNSString:(NSString *)__name
               withInt:(int)__ordinal {
  if ((self = [super initWithNSString:__name withInt:__ordinal])) {
    self->jceId_ = jceId != nil ? jceId : [self name];
  }
  return self;
}

- (NSString *)getJceId {
  return jceId_;
}

+ (void)initialize {
  if (self == [ComKloudtekUtilCryptoSymmetricAlgorithmEnum class]) {
    ComKloudtekUtilCryptoSymmetricAlgorithmEnum_AES = [[ComKloudtekUtilCryptoSymmetricAlgorithmEnum alloc] initWithNSString:@"AES" withInt:0];
    ComKloudtekUtilCryptoSymmetricAlgorithmEnum_initialized = YES;
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithObjects:ComKloudtekUtilCryptoSymmetricAlgorithmEnum_values count:1 type:[IOSClass classWithClass:[ComKloudtekUtilCryptoSymmetricAlgorithmEnum class]]];
}

+ (ComKloudtekUtilCryptoSymmetricAlgorithmEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < 1; i++) {
    ComKloudtekUtilCryptoSymmetricAlgorithmEnum *e = ComKloudtekUtilCryptoSymmetricAlgorithmEnum_values[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "SymmetricAlgorithm", NULL, 0x2, NULL },
    { "initWithNSString:", "SymmetricAlgorithm", NULL, 0x2, NULL },
    { "getJceId", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Lcom.kloudtek.util.crypto.SymmetricAlgorithm;"};
  static J2ObjcClassInfo _ComKloudtekUtilCryptoSymmetricAlgorithmEnum = { "SymmetricAlgorithm", "com.kloudtek.util.crypto", NULL, 0x4011, 3, methods, 0, NULL, 1, superclass_type_args};
  return &_ComKloudtekUtilCryptoSymmetricAlgorithmEnum;
}

@end
