//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/crypto/SymmetricAlgorithm.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _ComKloudtekUtilCryptoSymmetricAlgorithm_H_
#define _ComKloudtekUtilCryptoSymmetricAlgorithm_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef enum {
  ComKloudtekUtilCryptoSymmetricAlgorithm_AES = 0,
} ComKloudtekUtilCryptoSymmetricAlgorithm;

@interface ComKloudtekUtilCryptoSymmetricAlgorithmEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *jceId_;
}
+ (IOSObjectArray *)values;
+ (ComKloudtekUtilCryptoSymmetricAlgorithmEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;

- (id)initWithNSString:(NSString *)jceId
          withNSString:(NSString *)__name
               withInt:(int)__ordinal;

- (NSString *)getJceId;
@end

FOUNDATION_EXPORT BOOL ComKloudtekUtilCryptoSymmetricAlgorithmEnum_initialized;
J2OBJC_STATIC_INIT(ComKloudtekUtilCryptoSymmetricAlgorithmEnum)

FOUNDATION_EXPORT ComKloudtekUtilCryptoSymmetricAlgorithmEnum *ComKloudtekUtilCryptoSymmetricAlgorithmEnum_values[];

#define ComKloudtekUtilCryptoSymmetricAlgorithmEnum_AES ComKloudtekUtilCryptoSymmetricAlgorithmEnum_values[ComKloudtekUtilCryptoSymmetricAlgorithm_AES]
J2OBJC_STATIC_FIELD_GETTER(ComKloudtekUtilCryptoSymmetricAlgorithmEnum, AES, ComKloudtekUtilCryptoSymmetricAlgorithmEnum *)

J2OBJC_FIELD_SETTER(ComKloudtekUtilCryptoSymmetricAlgorithmEnum, jceId_, NSString *)

#endif // _ComKloudtekUtilCryptoSymmetricAlgorithm_H_
