//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/UnexpectedException.java
//
//  Created by yinkaf on 6/14/14.
//

#include "UnexpectedException.h"
#include "java/lang/Throwable.h"

@implementation KTUtilUnexpectedException

- (id)init {
  return [super init];
}

- (id)initWithNSString:(NSString *)message {
  return [super initWithNSString:message];
}

- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  return [super initWithNSString:message withJavaLangThrowable:cause];
}

- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause {
  return [super initWithJavaLangThrowable:cause];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "UnexpectedException", NULL, 0x1, NULL },
    { "initWithNSString:", "UnexpectedException", NULL, 0x1, NULL },
    { "initWithNSString:withJavaLangThrowable:", "UnexpectedException", NULL, 0x1, NULL },
    { "initWithJavaLangThrowable:", "UnexpectedException", NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _KTUtilUnexpectedException = { "UnexpectedException", "com.kloudtek.util", NULL, 0x1, 4, methods, 0, NULL, 0, NULL};
  return &_KTUtilUnexpectedException;
}

@end
