//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/kloudtek/util/UnexpectedException.java
//
//  Created by yannick on 28/12/13.
//

#include "UnexpectedException.h"
#include "java/lang/Throwable.h"

@implementation KTUtilsUnexpectedException

- (id)init {
  return [super init];
}

- (id)initWithNSString:(NSString *)message {
  return [super initWithNSString:message];
}

- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  return [super initWithNSString:message withJavaLangThrowable:cause];
}

- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause {
  return [super initWithJavaLangThrowable:cause];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _KTUtilsUnexpectedException = { "UnexpectedException", "com.kloudtek.util", NULL, 0x1, 0, NULL, 0, NULL, 0, NULL};
  return &_KTUtilsUnexpectedException;
}

@end
