//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/com/kloudtek/util/URLBuilder.java
//
//  Created by yinkaf on 6/14/14.
//

#ifndef _KTUtilURLBuilder_H_
#define _KTUtilURLBuilder_H_

@class IOSObjectArray;
@class JavaNetURI;
@class JavaNetURL;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface KTUtilURLBuilder : NSObject {
 @public
  NSString *baseUrl_;
  id<JavaUtilList> parameters_;
}

- (id)initWithNSString:(NSString *)url;

- (id)initWithNSString:(NSString *)baseUrl
     withNSStringArray:(IOSObjectArray *)path;

- (NSString *)getBaseUrl;

- (id<JavaUtilList>)getParameters;

- (KTUtilURLBuilder *)addPathWithNSString:(NSString *)path;

- (KTUtilURLBuilder *)addWithNSString:(NSString *)key
                         withNSString:(NSString *)value;

- (KTUtilURLBuilder *)addWithNSString:(NSString *)key
                             withLong:(long long int)value;

- (KTUtilURLBuilder *)addWithNSString:(NSString *)key
                              withInt:(int)value;

- (KTUtilURLBuilder *)addWithNSString:(NSString *)key
                             withByte:(char)value;

- (KTUtilURLBuilder *)addWithNSString:(NSString *)key
                          withBoolean:(BOOL)value;

- (KTUtilURLBuilder *)addEncodedWithNSString:(NSString *)key
                                withNSString:(NSString *)value;

- (JavaNetURL *)toUrl;

- (JavaNetURI *)toUri;

- (NSString *)description;

- (NSString *)extractParamsWithNSString:(NSString *)baseUrl;

- (void)copyAllFieldsTo:(KTUtilURLBuilder *)other;

@end

__attribute__((always_inline)) inline void KTUtilURLBuilder_init() {}

J2OBJC_FIELD_SETTER(KTUtilURLBuilder, baseUrl_, NSString *)
J2OBJC_FIELD_SETTER(KTUtilURLBuilder, parameters_, id<JavaUtilList>)

typedef KTUtilURLBuilder ComKloudtekUtilURLBuilder;

@interface KTUtilURLBuilder_Param : NSObject {
 @public
  NSString *key_;
  NSString *value_;
}

- (id)initWithKTUtilURLBuilder:(KTUtilURLBuilder *)outer$
                  withNSString:(NSString *)key
                  withNSString:(NSString *)value;

- (void)copyAllFieldsTo:(KTUtilURLBuilder_Param *)other;

@end

__attribute__((always_inline)) inline void KTUtilURLBuilder_Param_init() {}

J2OBJC_FIELD_SETTER(KTUtilURLBuilder_Param, key_, NSString *)
J2OBJC_FIELD_SETTER(KTUtilURLBuilder_Param, value_, NSString *)

#endif // _KTUtilURLBuilder_H_
