//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: _java/URLDecoder.java
//
//  Created by yinkaf on 6/11/14.
//

#ifndef _JavaNetURLDecoder_H_
#define _JavaNetURLDecoder_H_

#import "JreEmulation.h"

@interface JavaNetURLDecoder : NSObject {
}

+ (NSString *)decodeWithNSString:(NSString *)s;

+ (NSString *)decodeWithNSString:(NSString *)s
                    withNSString:(NSString *)enc;

- (id)init;

@end

__attribute__((always_inline)) inline void JavaNetURLDecoder_init() {}

FOUNDATION_EXPORT NSString *JavaNetURLDecoder_dfltEncName_;
J2OBJC_STATIC_FIELD_GETTER(JavaNetURLDecoder, dfltEncName_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(JavaNetURLDecoder, dfltEncName_, NSString *)

#endif // _JavaNetURLDecoder_H_
