//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: URLDecoder.java
//
//  Created by yannick on 06/01/14.
//

#ifndef _JavaNetURLDecoder_H_
#define _JavaNetURLDecoder_H_

#import "JreEmulation.h"

@interface JavaNetURLDecoder : NSObject {
}

+ (NSString *)dfltEncName;
+ (void)setDfltEncName:(NSString *)dfltEncName;
+ (NSString *)decodeWithNSString:(NSString *)s;
+ (NSString *)decodeWithNSString:(NSString *)s
                    withNSString:(NSString *)enc;
- (id)init;
@end

#endif // _JavaNetURLDecoder_H_
